name: post-commit-data
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.2
      - run: |
            echo "hihi" >> todo.txt
            git add .
            git commit -m "Auto updating TODO.txt"
            git push origin

